Correct argument order for 'mount'

diff --git a/fdemutool b/fdemutool
--- a/fdemutool
+++ b/fdemutool
@@ -22,6 +22,8 @@ function usage() {
 	echo "Mount/Read/Write Floppy Emulation USB sticks"
 	echo "A cheap script to easier handle this annoying format"
 	echo
+	echo " - USE WITH EXTREME CATION - "
+	echo
 	echo "Usage: $me <mode> [in] [out] [slot]"
 	echo
 	echo "Modes:"
@@ -34,8 +36,8 @@ function usage() {
 	echo
 	echo "Example:"
 	echo "  $me copy ~/floppy_disk/ disk1.img"
-	echo "  $me write foo.img /dev/usb3 1"
-	echo "  $me mount /dev/usb3 /mnt/fd 1"
+	echo "  $me write disk1.img /dev/usb3 1"
+	echo "  $me mount /dev/usb3 1 /mnt/fd"
 	echo
 	echo "For some interesting information, see"
 	echo "http://goughlui.com/2013/04/24/review-unbranded-1-44mb-usb-100-floppy-emulator/"
@@ -43,22 +45,22 @@ function usage() {
 
 function do_new() {
 	local out="$1"
-	if [ -z "$out" ]
-	then
+
+	if [ -z "$out" ]; then
 		usage
 		exit 1
 	fi
+
 	dd ${floppy_params} if=/dev/zero of="$out"
 	mkfs.msdos "$out"
-	if [ $? = 0 ]
-	then
+
+	if [ $? = 0 ]; then
 		du -sk "$out"
 	fi
 }
 
 function do_copy() {
-	if [ "$UID" != "0" ]
-	then
+	if [ "$UID" != "0" ]; then
 		echo "Sorry, I need root priveleges to mount an image" >&2
 		exit 1
 	fi
@@ -66,14 +68,12 @@ function do_copy() {
 	local in="$1"
 	local out="$2"
 
-	if [ -z "$in" -o -z "$out" ]
-	then
+	if [ -z "$in" -o -z "$out" ]; then
 		usage
 		exit 1
 	fi
 
-	if [ ! -e "$in" ]
-	then
+	if [ ! -e "$in" ]; then
 		echo "\"$in\": doesn't exist" >&2
 		exit 1
 	fi
@@ -81,15 +81,13 @@ function do_copy() {
 	srcsize=$(du -sk "$in" | cut -f 1)
 
 	echo "Source size: ${srcsize}K"
-	if [ $srcsize -ge $block_count ]
-	then
+	if [ $srcsize -ge $block_count ]; then
 		echo -n "\"$in\": ${srcsize}K: "
 		echo "won't fit onto \"$out\" ${block_count}" >&2
 		exit 1
 	fi
 
-	if [ ! -e "$out" ]
-	then
+	if [ ! -e "$out" ]; then
 		do_new "$out"
 	else
 		echo "Note: \"$out\": already exists"
@@ -99,14 +97,12 @@ function do_copy() {
 	mount "$out" "$tmp_mount" 
 
 	ret=$?
-	if [ "$ret" -ne 0 ]
-	then
+	if [ "$ret" -ne 0 ]; then
 		echo "mount \"$out\" \"$tmp_mount\": Failure: $ret" >&2
 		exit $ret
 	fi
 
-	if [ -d "$in" ]
-	then
+	if [ -d "$in" ]; then
 		cp -rv "$in/"* "$tmp_mount/"
 	else
 		cp -v "$in" "$tmp_mount/"
@@ -121,21 +117,20 @@ function do_write() {
 	local out=$2
 	local slot=$3
 
-	if [ -z "$in" -o -z "$out" -o -z "$slot" ]
-	then
+	if [ -z "$in" -o -z "$out" -o -z "$slot" ]; then
 		usage
 		exit 1
 	fi
 
-	if [ ! -e "$in" ]
-	then
+	if [ ! -e "$in" ]; then
 		echo "\"$in\": doesn't exist" >&2
 		exit 1
 	fi
-	if [ -e "$out" ]
-	then
+
+	if [ -e "$out" ]; then
 		echo "Note: \"$out\": already exists" >&2
 	fi
+
 	case "$slot" in
 	    ''|*[!0-9]*) 
 	    	echo "\"$slot\": Not a number" >&2
@@ -152,8 +147,7 @@ function do_write() {
 }
 
 function do_mount() {
-	if [ "$UID" != "0" ]
-	then
+	if [ "$UID" != "0" ]; then
 		echo "Sorry, I need root priveleges to mount an image" >&2
 		exit 1
 	fi
@@ -162,14 +156,12 @@ function do_mount() {
 	local out=$2
 	local slot=$3
 
-	if [ -z "$in" -o -z "$out" -o -z "$slot" ]
-	then
+	if [ -z "$in" -o -z "$out" -o -z "$slot" ]; then
 		usage
 		exit 1
 	fi
 
-	if [ ! -e "$in" ]
-	then
+	if [ ! -e "$in" ]; then
 		echo "\"$in\": doesn't exist" >&2
 		exit 1
 	fi
@@ -185,31 +177,39 @@ function do_mount() {
 
 	let offset="$block_size * ($block_count + $disk_padding) * $slot"
 	echo mount -o loop,offset=${offset},sizelimit=${fs_limit} -t msdos "$in" "$out"
+
 	mount -o loop,offset=${offset},sizelimit=${fs_limit} \
 	      -t msdos \
 	      "$in" \
 	      "$out"
+
+	ret="$?"
+
+	if [ "$ret" = "32" ]; then
+		echo -n "Failed to mount \"$in\", slot $slot. "
+		echo "Does that slot exist?" >&2
+		return $ret
+	fi
 }
 mode=$1
 shift
 
-echo "Mode: $mode"
-
-if [ "$mode" = "new" ]
-then
-	do_new "$1"
-elif [ "$mode" = "copy" ]
-then
-	do_copy "$1" "$2"
-elif [ "$mode" = "write" ]
-then
-	do_write  "$1" "$2" "$3"
-elif [ "$mode" = "mount" ]
-then
-	do_mount "$1" "$2" "$3"
-else
-	usage
-	exit 1
-fi
+case "$mode" in
+	"new")
+		do_new "$1"
+		;;
+	"copy")
+		do_copy "$1" "$2"
+		;;
+	"write")
+		do_write  "$1" "$2" "$3"
+		;;
+	"mount")
+		do_mount "$1" "$3" "$2"
+		;;
+	*)
+		usage
+		exit 1
+esac
 
 echo "Finished"
