Rename, some cleanups

diff --git a/fdemutool b/fdemutool
--- a/fdemutool
+++ b/fdemutool
@@ -1,4 +1,7 @@
 #!/usr/bin/env bash
+# Obtw, the mounting code needs loopback support in your kernel.
+# By gammy
+# 
 # Based on: 
 # http://goughlui.com/2013/04/24/review-unbranded-1-44mb-usb-100-floppy-emulator/
 
@@ -6,11 +9,19 @@ block_size=1024
 block_count=1440
 disk_padding=96
 
+deps=(dd mount mkfs.msdos )
+for dep in ${deps[@]}; do
+        which $dep > /dev/null || exit $?
+done
+
 floppy_params="bs=${block_size} count=${block_count}"
 let fs_limit="$block_size * $block_count"
 
 function usage() {
 	local me=$(basename $0)
+	echo "Mount/Read/Write Floppy Emulation USB sticks"
+	echo "A cheap script to easier handle this annoying format"
+	echo
 	echo "Usage: $me <mode> [in] [out] [slot]"
 	echo
 	echo "Modes:"
@@ -22,11 +33,12 @@ function usage() {
 	echo "mount: Mount [in], [slot] to [out]"
 	echo
 	echo "Example:"
-       	echo "  $me new foo.img"
-	echo "  $me copy ~/floppy_disk/ foo.img"
-	echo "  $me write foo.img usb_img.img 1"
-	echo "  $me mount usb_img.img 1"
-	echo "  $ dd usb_img.img /dev/my_usb"
+	echo "  $me copy ~/floppy_disk/ disk1.img"
+	echo "  $me write foo.img /dev/usb3 1"
+	echo "  $me mount /dev/usb3 /mnt/fd 1"
+	echo
+	echo "For some interesting information, see"
+	echo "http://goughlui.com/2013/04/24/review-unbranded-1-44mb-usb-100-floppy-emulator/"
 }
 
 function do_new() {
@@ -47,7 +59,7 @@ function do_new() {
 function do_copy() {
 	if [ "$UID" != "0" ]
 	then
-		echo "Sorry, I need root priveleges to mount an image"
+		echo "Sorry, I need root priveleges to mount an image" >&2
 		exit 1
 	fi
 
@@ -62,34 +74,44 @@ function do_copy() {
 
 	if [ ! -e "$in" ]
 	then
-		echo "\"$in\": doesn't exist"
-		exit 1
-	fi
-	srcsize=$(du -sk "$in" | cut -f 1)
-	echo "Source size: ${srcsize}K"
-	if [ $srcsize -ge $block_count ]
-	then
-		echo "\"$in\": ${srcsize}K: won't fit onto \"$out\""
+		echo "\"$in\": doesn't exist" >&2
 		exit 1
 	fi
 
-	tmp_img="$out" # $(mktemp)
+	srcsize=$(du -sk "$in" | cut -f 1)
+
+	echo "Source size: ${srcsize}K"
+	if [ $srcsize -ge $block_count ]
+	then
+		echo -n "\"$in\": ${srcsize}K: "
+		echo "won't fit onto \"$out\" ${block_count}" >&2
+		exit 1
+	fi
+
 	if [ ! -e "$out" ]
 	then
-		do_new "$tmp_img"
+		do_new "$out"
 	else
 		echo "Note: \"$out\": already exists"
 	fi
+
 	tmp_mount=$(mktemp --directory)
-	mount "$tmp_img" "$tmp_mount" 
+	mount "$out" "$tmp_mount" 
+
 	ret=$?
 	if [ "$ret" -ne 0 ]
 	then
-		echo "mount \"$tmp_img\" \"$tmp_mount\": Failure: $ret"
+		echo "mount \"$out\" \"$tmp_mount\": Failure: $ret" >&2
 		exit $ret
 	fi
-	find "$in" -exec cp -v "{}" "$tmp_mount/" \;
-	#cp -rv "$in/"* "$tmp_mount/"
+
+	if [ -d "$in" ]
+	then
+		cp -rv "$in/"* "$tmp_mount/"
+	else
+		cp -v "$in" "$tmp_mount/"
+	fi	
+
 	umount "$tmp_mount"
 	rm -rf "$tmp_mount"
 }
@@ -107,23 +129,23 @@ function do_write() {
 
 	if [ ! -e "$in" ]
 	then
-		echo "\"$in\": doesn't exist"
+		echo "\"$in\": doesn't exist" >&2
 		exit 1
 	fi
 	if [ -e "$out" ]
 	then
-		echo "Note: \"$out\": already exists"
+		echo "Note: \"$out\": already exists" >&2
 	fi
 	case "$slot" in
 	    ''|*[!0-9]*) 
-	    	echo "\"$slot\": Not a number" 
+	    	echo "\"$slot\": Not a number" >&2
 		exit 1
 		;;
 	    *) 
 	    	;;
 	esac
 
-	let offset="(${block_count} + ${padding}) * $slot"
+	let offset="(${block_count} + ${disk_padding}) * $slot"
 	echo "Copy \"$in\" to \"$out\", slot $slot"
 	echo dd ${floppy_params} seek="$offset" if="$in" of="$out"
 	dd ${floppy_params} seek="$offset" if="$in" of="$out"
@@ -132,7 +154,7 @@ function do_write() {
 function do_mount() {
 	if [ "$UID" != "0" ]
 	then
-		echo "Sorry, I need root priveleges to mount an image"
+		echo "Sorry, I need root priveleges to mount an image" >&2
 		exit 1
 	fi
 
@@ -148,23 +170,25 @@ function do_mount() {
 
 	if [ ! -e "$in" ]
 	then
-		echo "\"$in\": doesn't exist"
+		echo "\"$in\": doesn't exist" >&2
 		exit 1
 	fi
 
 	case "$slot" in
 	    ''|*[!0-9]*) 
-	    	echo "\"$slot\": Not a number" 
+	    	echo "\"$slot\": Not a number" >&2
 		exit 1
 		;;
 	    *) 
 	    	;;
 	esac
 
-	#echo "Mount \"$in\" to \"$out\", slot $slot"
 	let offset="$block_size * ($block_count + $disk_padding) * $slot"
 	echo mount -o loop,offset=${offset},sizelimit=${fs_limit} -t msdos "$in" "$out"
-	mount -o loop,offset=${offset},sizelimit=${fs_limit} -t msdos "$in" "$out"
+	mount -o loop,offset=${offset},sizelimit=${fs_limit} \
+	      -t msdos \
+	      "$in" \
+	      "$out"
 }
 mode=$1
 shift
@@ -188,5 +212,4 @@ else
 	exit 1
 fi
 
-
-
+echo "Finished"
